### ISSUE TITLE
Support cluster mode

### ISSUE THREAD

**Issue by showermat** [SparkTC/spark-bench#107]
It looks like there hasn't been much thought put into supporting cluster mode in Spark-bench, which may be useful in some cases.  In particular, Spark on Kubernetes currently only works in cluster mode, so this is a precondition for supporting the Kubernetes scheduler.

**Comment by ecurtin** [comment]
Thank you for filing this, @showermat!

One way in which this affects spark-bench in particular is that the temporary "split" configs aren't necessarily written to the driver so they don't get passed around properly. 

Two possible fixes:
1. Have the temp files write to HDFS, or
2. Instead of writing temp files and passing a file path to them, pass the config as one giant child argument to spark-submit.

**Comment by ecurtin** [comment]
A workaround for this is putting spark-bench jars in hdfs.

**Comment by ecurtin** [comment]
Placing the Spark-Bench jars in HDFS and having all files be written to HDFS seems to solve this issue. I am closing this issue for now, but I welcome any bug reports if this does not work for you!
