### ISSUE TITLE
LablePropagation

### ISSUE THREAD

**Issue by jthimer** [SparkTC/spark-bench#19]
Can someone confirm if LabelPropagation takes any HDFS input and/or generate HDFS output?

It's folder does not seem to have a datagen routine (which I think answers my first question), and my build doesn't seem to generate any HDFS output either.  Inspecting the code "LabelPropagationApp.scala" does not seem to ever use/pass the values "input" (args[0]) or "output"  (args[1]).

**Comment by ecurtin** [comment]
Thanks for submitting an issue to spark-bench!

Spark-bench has recently gone through a major rewrite, and it looks like this issue is targeted towards the legacy version. As a note, the new version accepts input and writes output to any source that Spark is able to read/write to, including local files, HDFS, S3, etc.

If you'd like to reopen this issue for examination against the legacy branch feel free, but I am going to close this for now due to inactivity.
