### ISSUE TITLE
"exectuor" → executor

### ISSUE THREAD

**Issue by pietrodn** [SparkTC/spark-bench#21]
Spelling error on "exectuor-memory" here: https://github.com/SparkTC/spark-bench/blob/master/PageRank/bin/yarn-run.sh#L28
It makes the script fail.

**Comment by ecurtin** [comment]
Thanks for submitting an issue to spark-bench!

Spark-bench has recently gone through a major rewrite, and it looks like this issue is targeted towards the legacy version. 

If you'd like to reopen this issue for examination against the legacy branch feel free, but I am going to close this for now due to inactivity.
