### ISSUE TITLE
Can this suite be made available to run in a Jupyter notebook?

### ISSUE THREAD

**Issue by dustinvanstee** [SparkTC/spark-bench#25]
I am using a spark cloud service with minimal access to the command line.  I was wondering if a version of this benchmark could be designed as a notebook.  Then it would be very portable for me to test many cloud implementations.  Thanks

**Comment by ecurtin** [comment]
Thanks for submitting an issue to spark-bench!

Spark-bench has recently gone through a major rewrite, and it looks like this issue is targeted towards the legacy version. 

If you'd like to reopen this issue for examination against the legacy branch feel free, but I am going to close this for now due to inactivity.
