### ISSUE TITLE
Spark 2.0 dataframes support

### ISSUE THREAD

**Issue by jthimer** [SparkTC/spark-bench#29]
Wondering if the team is considering updating SparkBench that can leverage "dataframes" (esp. for MLlib benchmarks) now that Spark 2.0 has been released.

http://spark.apache.org/releases/spark-release-2-0-0.html

**Comment by ecurtin** [comment]
Thanks for submitting an issue to spark-bench!

Spark-bench has recently gone through a major rewrite, and it looks like this issue is targeted towards the legacy version. 

If you'd like to reopen this issue for examination against the legacy branch feel free, but I am going to close this for now due to inactivity.

As a note, the new version of spark-bench is built around the concept of workloads that use Dataframes. Take a look! Contributions welcome!
