### ISSUE TITLE
Mistake in ReadMe File for streaming.

### ISSUE THREAD

**Issue by shujamughal** [SparkTC/spark-bench#31]
Hi,

Instead of SQL, it should be streaming in following line.

Note for streaming applications For Streaming applications such as TwitterTag,StreamingLogisticRegression First, execute <SPARK_BENCH_HOME>/SQL/bin/gen_data.sh in one terminal; Second, execute <SPARK_BENCH_HOME>/SQL/bin/run.sh in another terminal;

**Comment by ecurtin** [comment]
Thanks for submitting an issue to spark-bench!

Spark-bench has recently gone through a major rewrite, and it looks like this issue is targeted towards the legacy version. 

If you'd like to reopen this issue for examination against the legacy branch feel free, but I am going to close this for now due to inactivity.
