### ISSUE TITLE
Terasort data generation

### ISSUE THREAD

**Issue by zakkak** [SparkTC/spark-bench#36]
https://github.com/SparkTC/spark-bench/commit/fa1aa4547577c0abead71c20ca3e7a79128f1baf appears to break input data generation for Terasort (commented out `echo_and_run` line in `bin/gen_data.sh`).

**Comment by ecurtin** [comment]
Thanks for submitting an issue to spark-bench!

Spark-bench has recently gone through a major rewrite, and it looks like this issue is targeted towards the legacy version. 

If you'd like to reopen this issue for examination against the legacy branch feel free, but I am going to close this for now due to inactivity.
