### ISSUE TITLE
report_output:error: gen_report input variables less than 6

### ISSUE THREAD

**Issue by RayOsLei** [SparkTC/spark-bench#48]
when i execute the following command:

```
<SPARK_BENCH_HOME>/<Workload>/bin/gen_data.sh
<SPARK_BENCH_HOME>/<Workload>/bin/run.sh
```
i got error from `num/bench-report.dat`

```
##Apptype,start_ts,duration,size,throughput,resStatus,AppType,nExe,driverMem,exeMem,exeCore,nPar,nIter,memoryFraction,numRecords(size)
error: gen_report input variables less than 6
,Terasort-MLlibConfig,,,,,2,3,,1000
#Apptype,start_ts,duration,size,throughput,resStatus,AppType,nExe,driverMem,exeMem,exeCore,nPar,nIter,memoryFraction,numRecords(size)
error: gen_report input variables less than 6
,Terasort-MLlibConfig,,,,,2,3,,1000

```

**Comment by ecurtin** [comment]
Thanks for submitting an issue to spark-bench!

Spark-bench has recently gone through a major rewrite, and it looks like this issue is targeted towards the legacy version. 

If you'd like to reopen this issue for examination against the legacy branch feel free, but I am going to close this for now due to inactivity.
