### ISSUE TITLE
common does not compile

### ISSUE THREAD

**Issue by abedad** [SparkTC/spark-bench#9]
When running build-all.sh it fails in the first module "common" and skips all other modules. I had to remove it from modules in pom.xml in order to compile the bench

**Comment by jthimer** [comment]
I have the same problem.  The cause seems to be due to the dependency in "common/DataGen/pom.xml" 

       <groupId>edu.jhu.nlp</groupId>
        <artifactId>wikixmlj</artifactId>
        <version>1.0</version>
    </dependency>

However, the directory "nlp" is currently missing (or has been removed) from the repository at

https://oss.sonatype.org/content/groups/scala-tools/edu/jhu

so neither "wikixmlj/pom.xml" or it's jar can be found and downloaded.

**Comment by lm4limin** [comment]
as mentioned in the readme:

Download wikixmlj package: cd to a directory for download and type the next commands

    git clone https://github.com/synhershko/wikixmlj.git
    cd wikixmlj
    mvn package install
